#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '🏗️👷 Checking styles and testing your project before committing'
npm run check-format || (
	echo '🤡😂❌🤡 Failed Formating. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;  
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'